name: flutter_consulting_platform
description: A consulting platform project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  get: ^4.6.5
  get_storage: ^2.0.3
  phosphor_flutter: ^1.4.0
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/images/
    - asset/images/pngs/
    - asset/images/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: asset/fonts/poppins/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: asset/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: asset/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: asset/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: asset/fonts/poppins/Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: asset/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: asset/fonts/poppins/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: asset/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: asset/fonts/poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: asset/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: asset/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: asset/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: asset/fonts/poppins/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
    - family: Cairo
      fonts:
        - asset: asset/fonts/cario/Cairo-VariableFont_wght.ttf
