Map<String, String> arabic = {
  'Pushed': 'لقد قمت بالضغط على هذا الزر هذا العدد من مرات:',
  'ChangeLanguage': 'تغيير اللغة',
  'PressMe': 'اضغط علي',
  'Valid': 'صالح',
  'Invalid': 'غير صالح',
  'Phone': 'رقم الهاتف',
  'NewToApp': 'جديد في التطبيق',
  'Password': 'كلمة المرور',
  'Email': 'البريد الإلكتروني',
  'Login': 'تسجيل الدخول',
  'Register': 'تسجيل',
  'FullName': 'الاسم الكامل',
  'ConfirmPassword': 'تأكيد كلمة المرور',
  'User': 'مستخدم',
  'Specialist': 'مختص',
  'AlreadyHaveAccount': 'هل تمتلك حساباً بالفعل؟',
  'CreateNewAccount': 'انشاء حساب جديد',
  'Thisfieldrequired': 'هذا الحقل مطلوب',
};
