Map<String, String> arabic = {
  'Pushed': 'لقد قمت بالضغط على هذا الزر هذا العدد من مرات:',
  'ChangeLanguage': 'تغيير اللغة',
  'PressMe': 'اضغط علي',
  'Valid': 'صالح',
  'Invalid': 'غير صالح',
  'Phone': 'رقم الهاتف',
  'NewToApp': 'جديد في التطبيق',
  'Password': 'كلمة المرور',
  'Email': 'البريد الإلكتروني',
  'Login': 'تسجيل الدخول',
  'Register': 'تسجيل',
  'FullName': 'الاسم الكامل',
  'ConfirmPassword': 'تأكيد كلمة المرور',
  'User': 'مستخدم',
  'Specialist': 'مختص',
  'AlreadyHaveAccount': 'هل تمتلك حساباً بالفعل؟',
  'CreateNewAccount': 'انشاء حساب جديد',
  'Thisfieldrequired': 'هذا الحقل مطلوب',
  'NewEmail': 'البريد الإلكتروني الجديد',
  'Change': 'تغيير',
  'OldPassword': 'كلمة المرور القديمة',
  'NewPassword': 'كلمة المرور الجديدة',
  'Change Password': 'تغير كلمة المرور',
  'Change Email': 'تغير الحساب الإلكتروني',
  'NewPhone': 'رقم الهاتف الجديد',
  'Change Phone': 'تغير رقم الهاتف',
  'Search': 'بحث',
  'Categories': 'التصنيفات',
  'Specialists': 'الإختصاصيون',
  'AddAbout': 'إضافة حول',
  'AddContacts': 'إضافة معلومات تواصل',
  'Specializes': 'الإختصاصات',
  'ContactInfos': 'معلومات التواصل',
  'Schedule': 'جدول المواعيد',
  'PleaseAddSpecializes': 'يرجى إضافة إختصاصات',
  'ShowMore': 'المزيد',
  'ShowLess': 'طي',
};
