Map<String, String> english = {
  'Pushed': 'You have pushed the button this many times:',
  'ChangeLanguage': 'Change Language',
  'PressMe': 'Press Me',
  'Valid': 'Valid',
  'Invalid': 'Invalid',
  'Phone': 'Phone number',
  'NewToApp':'NewToApp?',
  'Password':'Password',
  'Email':'Email',
  'Login':'Login',
  'Register':'Register',
  'FullName':'Full Name',
  'ConfirmPassword':'Confirm Password',
  'User':'User',
  'Specialist':'Specialist',
};
